"""Phase 2: perfect-foresight upper bounds (diagnostic only -- not a policy).

Oracle A: independent per-battery exact DP using the REAL realized RT price
trajectory for that instance (network constraints ignored -- optimistic).

Oracle B: network-feasible perfect-foresight LP over the whole horizon using
the same realized RT trajectory, with PTDF flow constraints (scipy HiGHS).
The quadratic degradation cost term is dropped in the LP objective (it is
economically negligible at this problem's scale: KAPPA_DEG*(power*dt/capacity)^2
with power/capacity ~ 0.25 gives ~1e-5 $ per MW of action, vs price terms of
tens of dollars) -- this makes Oracle B a very slightly optimistic, clearly
labeled upper bound, not a claimed exact optimum.

The realized RT price trajectory is generated by the episode RNG independently
of any policy's actions (verified from challenge.py: take_step's next-seed draw
happens before the action-dependent state update, and price generation only
consumes that seed) -- so it can be recorded once with any placeholder policy.
"""
import sys
from pathlib import Path

import numpy as np

_SANDBOX_DIR = Path(__file__).resolve().parent
_ID7_DIR = _SANDBOX_DIR.parent
_PKGROOT = _SANDBOX_DIR / "_pkgroot"
sys.path.insert(0, str(_PKGROOT))
sys.path.insert(0, str(_ID7_DIR))

from competition.energy_arbitrage.python.challenge import Challenge, Track, NextRTPricesGenerate
from competition.energy_arbitrage.python.scenarios import Scenario

import benchmark as bch
import policy_v4
import policy_v2

_DT = 0.25
_KAPPA_TX = 0.25
_KAPPA_DEG = 1.0
_BETA_DEG = 2.0
MASTER_SEED = 123


def _record_rt_trajectory(ch):
    """RT prices don't depend on the policy's actions -- record them with a
    trivial zero-action stand-in policy."""
    view = ch.to_policy_view()
    import random
    rng = random.Random(); rng.seed(ch._hidden_seed)
    state = ch._initial_state(rng)
    rt = np.zeros((ch.num_steps, ch.network.num_nodes))
    exo = np.zeros((ch.num_steps, ch.network.num_nodes))
    for t in range(ch.num_steps):
        rt[t] = state.rt_prices
        exo[t] = state.exogenous_injections
        a = [0.0] * ch.num_batteries
        next_seed = bytes([rng.randint(0, 255) for _ in range(32)])
        state = ch.take_step(state, a, NextRTPricesGenerate(next_seed))
    return rt, exo


def oracle_a(ch, rt_traj, S=81, A=41):
    """Independent per-battery exact DP, network-blind, using the REAL
    realized RT trajectory (not a forecast)."""
    B = ch.num_batteries
    T = ch.num_steps
    cap = np.array([b.capacity_mwh for b in ch.batteries])
    pchg = np.array([b.power_charge_mw for b in ch.batteries])
    pdis = np.array([b.power_discharge_mw for b in ch.batteries])
    etac = np.array([b.efficiency_charge for b in ch.batteries])
    etad = np.array([b.efficiency_discharge for b in ch.batteries])
    smin = np.array([b.soc_min_mwh for b in ch.batteries])
    smax = np.array([b.soc_max_mwh for b in ch.batteries])
    node = np.array([b.node for b in ch.batteries])
    soc_init = np.array([b.soc_initial_mwh for b in ch.batteries])

    soc_grid = smin[:, None] + (smax - smin)[:, None] * np.linspace(0.0, 1.0, S)[None, :]
    price = rt_traj[:, node]  # (T, B) -- exact realized price at each battery's node

    smin2, smax2 = smin[:, None], smax[:, None]
    headroom = np.maximum(smax2 - soc_grid, 0.0)
    avail = np.maximum(soc_grid - smin2, 0.0)
    max_charge = np.clip(np.minimum(headroom / (etac[:, None] * _DT), pchg[:, None]), 0.0, None)
    max_discharge = np.clip(np.minimum(avail * etad[:, None] / _DT, pdis[:, None]), 0.0, None)

    fracs = np.linspace(1.0 / (A // 2), 1.0, A // 2)
    neg = -max_charge[:, :, None] * fracs[::-1][None, None, :]
    pos = max_discharge[:, :, None] * fracs[None, None, :]
    zero = np.zeros((B, S, 1))
    u = np.concatenate([neg, zero, pos], axis=-1)  # (B, S, A)
    abs_u = np.abs(u)

    c = np.maximum(-u, 0.0); d = np.maximum(u, 0.0)
    new_soc = soc_grid[:, :, None] + etac[:, None, None] * c * _DT - d * _DT / etad[:, None, None]
    new_soc = np.clip(new_soc, smin[:, None, None], smax[:, None, None])
    span = np.maximum((smax - smin)[:, None, None], 1e-12)
    idx_frac = np.clip((new_soc - smin[:, None, None]) / span * (S - 1), 0.0, S - 1 - 1e-06)
    i0 = idx_frac.astype(np.intp)
    i1 = np.minimum(i0 + 1, S - 1)
    w = idx_frac - i0
    cost = _KAPPA_TX * abs_u * _DT + _KAPPA_DEG * (abs_u * _DT / cap[:, None, None]) ** _BETA_DEG
    b_idx = np.arange(B)[:, None, None]

    soc = soc_init.copy()
    total_profit = 0.0
    V_all = np.zeros((T + 1, B, S))
    V_next = np.zeros((B, S))
    for t in range(T - 1, -1, -1):
        Vc = V_next[b_idx, i0] * (1.0 - w) + V_next[b_idx, i1] * w
        reward = u * price[t][:, None, None] * _DT - cost
        total = reward + Vc
        V_here = np.max(total, axis=2)
        V_all[t] = V_here
        V_next = V_here

    for t in range(T):
        frac = np.clip((soc - smin) / (smax - smin) * (S - 1), 0.0, S - 1 - 1e-06)
        s0 = frac.astype(np.intp)
        s1 = np.minimum(s0 + 1, S - 1)
        sw = frac - s0
        best_action = np.zeros(B)
        # evaluate reward+Vc at the SOC-nearest grid row, pick that row's best action
        for i in range(B):
            lo, hi = s0[i], s1[i]
            row = lo if sw[i] < 0.5 else hi
            u_row = u[i, row]
            abs_u_row = np.abs(u_row)
            new_soc_row = np.clip(soc[i] + etac[i] * np.maximum(-u_row, 0) * _DT - np.maximum(u_row, 0) * _DT / etad[i], smin[i], smax[i])
            span_i = max(smax[i] - smin[i], 1e-12)
            f2 = np.clip((new_soc_row - smin[i]) / span_i * (S - 1), 0.0, S - 1 - 1e-06)
            j0 = f2.astype(np.intp); j1 = np.minimum(j0 + 1, S - 1); jw = f2 - j0
            Vc_row = V_all[t + 1, i, j0] * (1 - jw) + V_all[t + 1, i, j1] * jw
            reward_row = u_row * price[t, i] * _DT - _KAPPA_TX * abs_u_row * _DT - _KAPPA_DEG * (abs_u_row * _DT / cap[i]) ** _BETA_DEG
            best_j = np.argmax(reward_row + Vc_row)
            best_action[i] = u_row[best_j]
        c_i = np.maximum(-best_action, 0.0); d_i = np.maximum(best_action, 0.0)
        abs_a = np.abs(best_action)
        step_profit = best_action * price[t] * _DT - _KAPPA_TX * abs_a * _DT - _KAPPA_DEG * (abs_a * _DT / cap) ** _BETA_DEG
        total_profit += float(np.sum(step_profit))
        soc = np.clip(soc + etac * c_i * _DT - d_i * _DT / etad, smin, smax)

    return total_profit


def oracle_b(ch, rt_traj, exo_traj):
    """Network-feasible perfect-foresight LP (scipy HiGHS). Degradation cost
    is dropped from the objective (see module docstring) -- a small, clearly
    labeled optimistic approximation."""
    try:
        from scipy.optimize import linprog
    except ImportError:
        return None, "scipy unavailable"

    B = ch.num_batteries
    T = ch.num_steps
    cap = np.array([b.capacity_mwh for b in ch.batteries])
    pchg = np.array([b.power_charge_mw for b in ch.batteries])
    pdis = np.array([b.power_discharge_mw for b in ch.batteries])
    etac = np.array([b.efficiency_charge for b in ch.batteries])
    etad = np.array([b.efficiency_discharge for b in ch.batteries])
    smin = np.array([b.soc_min_mwh for b in ch.batteries])
    smax = np.array([b.soc_max_mwh for b in ch.batteries])
    node = np.array([b.node for b in ch.batteries])
    soc_init = np.array([b.soc_initial_mwh for b in ch.batteries])
    ptdf = np.asarray(ch.network.ptdf)
    limits = np.asarray(ch.network.flow_limits)
    slack = ch.network.slack_bus
    L = ptdf.shape[0]

    # variables: c[t,i] (charge, >=0), d[t,i] (discharge, >=0), flattened as
    # x = [c_00..c_0B, c_10..., ..., d_00..., ...]
    nvar = 2 * T * B
    def c_idx(t, i): return t * B + i
    def d_idx(t, i): return T * B + t * B + i

    price = rt_traj[:, node]  # (T,B)
    obj = np.zeros(nvar)
    for t in range(T):
        for i in range(B):
            obj[c_idx(t, i)] = -(-price[t, i] * _DT - _KAPPA_TX * _DT)  # cost of charging (minimize -profit)
            obj[d_idx(t, i)] = -(price[t, i] * _DT - _KAPPA_TX * _DT)

    bounds = [(0.0, pchg[i]) for t in range(T) for i in range(B)] + \
             [(0.0, pdis[i]) for t in range(T) for i in range(B)]

    A_ub_rows, b_ub = [], []
    for i in range(B):
        for t in range(T):
            row_hi = np.zeros(nvar)
            row_lo = np.zeros(nvar)
            for s in range(t + 1):
                row_hi[c_idx(s, i)] = etac[i] * _DT
                row_hi[d_idx(s, i)] = -_DT / etad[i]
                row_lo[c_idx(s, i)] = -etac[i] * _DT
                row_lo[d_idx(s, i)] = _DT / etad[i]
            A_ub_rows.append(row_hi); b_ub.append(smax[i] - soc_init[i])
            A_ub_rows.append(row_lo); b_ub.append(soc_init[i] - smin[i])

    for t in range(T):
        exo_now = exo_traj[t].copy()
        exo_now[slack] = 0.0
        base_flow = ptdf @ exo_now
        for l in range(L):
            row_hi = np.zeros(nvar)
            row_lo = np.zeros(nvar)
            for i in range(B):
                row_hi[d_idx(t, i)] = ptdf[l, node[i]]
                row_hi[c_idx(t, i)] = -ptdf[l, node[i]]
                row_lo[d_idx(t, i)] = -ptdf[l, node[i]]
                row_lo[c_idx(t, i)] = ptdf[l, node[i]]
            A_ub_rows.append(row_hi); b_ub.append(limits[l] - base_flow[l])
            A_ub_rows.append(row_lo); b_ub.append(limits[l] + base_flow[l])

    A_ub = np.array(A_ub_rows)
    b_ub = np.array(b_ub)

    res = linprog(obj, A_ub=A_ub, b_ub=b_ub, bounds=bounds, method="highs")
    if not res.success:
        return None, f"LP failed: {res.message}"
    return -res.fun, "ok"


def main():
    scen_list = [(Scenario.BASELINE, list(range(0, 50, 5))[:10]), (Scenario.CONGESTED, list(range(1, 51, 5))[:10])]
    results = []
    for scen, nonces in scen_list:
        for nonce in nonces:
            seed = bch.seed_from_master_nonce(MASTER_SEED, nonce)
            ch = Challenge.generate_instance(seed, Track(s=scen))
            rt_traj, exo_traj = _record_rt_trajectory(ch)
            _, baseline_profit = ch.compute_baseline()

            policy_v4._CACHE.clear()
            view = ch.to_policy_view()
            import random
            rng = random.Random(); rng.seed(ch._hidden_seed)
            state = ch._initial_state(rng)
            for t in range(ch.num_steps):
                a = policy_v4.policy(view, state)
                next_seed = bytes([rng.randint(0, 255) for _ in range(32)])
                state = ch.take_step(state, a, NextRTPricesGenerate(next_seed))
            v4_profit = state.total_profit

            oa = oracle_a(ch, rt_traj)
            ob, ob_status = oracle_b(ch, rt_traj, exo_traj)

            def q(p): return max(-10.0, min((p - baseline_profit) / (baseline_profit + 1e-6), 10.0))
            row = dict(nonce=nonce, scenario=scen.name, baseline=baseline_profit,
                       v4_profit=v4_profit, v4_quality=q(v4_profit),
                       oracle_a_profit=oa, oracle_a_quality=q(oa),
                       oracle_b_profit=ob, oracle_b_quality=(q(ob) if ob is not None else None),
                       oracle_b_status=ob_status)
            results.append(row)
            ob_str = f"{ob:12.1f} (q={q(ob):+7.3f})" if ob is not None else f"FAILED: {ob_status}"
            print(f"nonce={nonce:3d} {scen.name:9s} baseline={baseline_profit:10.1f} "
                  f"v4={v4_profit:10.1f}(q={q(v4_profit):+.3f}) "
                  f"oracleA={oa:12.1f}(q={q(oa):+7.3f}) oracleB={ob_str}")

    print("\n| Instance | Official baseline | policy_v4 | Independent oracle | Network oracle | Oracle quality (net) |")
    print("|---|---|---|---|---|---|")
    for r in results:
        obq = f"{r['oracle_b_quality']:+.3f}" if r['oracle_b_quality'] is not None else "N/A"
        obp = f"{r['oracle_b_profit']:.1f}" if r['oracle_b_profit'] is not None else "N/A"
        print(f"| {r['nonce']} | {r['baseline']:.1f} | {r['v4_profit']:.1f} | {r['oracle_a_profit']:.1f} | {obp} | {obq} |")

    import numpy as _np
    for scen_name in ["BASELINE", "CONGESTED"]:
        rows = [r for r in results if r["scenario"] == scen_name]
        oa_q = _np.mean([r["oracle_a_quality"] for r in rows])
        ob_qs = [r["oracle_b_quality"] for r in rows if r["oracle_b_quality"] is not None]
        ob_q = _np.mean(ob_qs) if ob_qs else None
        v4_q = _np.mean([r["v4_quality"] for r in rows])
        print(f"\n{scen_name}: mean oracle_A quality={oa_q:+.3f}  mean oracle_B quality={ob_q if ob_q is None else f'{ob_q:+.3f}'}  "
              f"mean v4 quality={v4_q:+.3f}  gap(A-v4)={oa_q - v4_q:+.3f}"
              + (f"  gap(B-v4)={ob_q - v4_q:+.3f}" if ob_q is not None else ""))

    import csv
    with open("oracle_analysis_results.csv", "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(results[0].keys()))
        w.writeheader()
        for r in results:
            w.writerow(r)


if __name__ == "__main__":
    main()
